# Generated by Django 5.0.6 on 2026-06-07 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=100, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=100, null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type', models.CharField(blank=True, max_length=100, null=True)),
                ('personality_traits', models.JSONField(blank=True, default=list)),
                ('mbti_personality', models.CharField(blank=True, choices=[('INTJ - The Architect', 'INTJ - The Architect'), ('INTP - The Logician', 'INTP - The Logician'), ('ENTJ - The Commander', 'ENTJ - The Commander'), ('ENTP - The Visionary', 'ENTP - The Visionary'), ('INFJ - The Advocate', 'INFJ - The Advocate'), ('INFP - The Idealist', 'INFP - The Idealist'), ('ENFJ - The Giver', 'ENFJ - The Giver'), ('ENFP - The Enthusiast', 'ENFP - The Enthusiast'), ('ISTJ - The Duty Fulfiller', 'ISTJ - The Duty Fulfiller'), ('ISFJ - The Protector', 'ISFJ - The Protector'), ('ESTJ - The Executive', 'ESTJ - The Executive'), ('ESFJ - The Caregiver', 'ESFJ - The Caregiver'), ('ISTP - The Craftsman', 'ISTP - The Craftsman'), ('ISFP - The Artist', 'ISFP - The Artist')], max_length=100, null=True)),
                ('enneagram_personality', models.CharField(blank=True, choices=[('1 - The Reformer', '1 - The Reformer'), ('2 - The Helper', '2 - The Helper'), ('3 - The Achiever', '3 - The Achiever'), ('4 - The Romantic', '4 - The Romantic'), ('5 - The Investigator', '5 - The Investigator'), ('6 - The Skeptic', '6 - The Skeptic'), ('7 - The Enthusiast', '7 - The Enthusiast'), ('8 - The Challenger', '8 - The Challenger'), ('9 - The Peacemaker', '9 - The Peacemaker')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlotPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
                ('order', models.SmallIntegerField(blank=True, default=1)),
                ('plot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.plot')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
                ('premise', models.CharField(max_length=250, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('date_started', models.DateField(auto_now_add=True)),
                ('date_last_saved', models.DateField(auto_now=True)),
                ('date_finished', models.DateField(null=True)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('order', models.SmallIntegerField(blank=True, default=1)),
                ('characters', models.ManyToManyField(blank=True, to='app.character')),
                ('plotpoint', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.plotpoint')),
                ('story', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
        ),
        migrations.AddField(
            model_name='plot',
            name='story',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='app.story'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.story'),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500, null=True)),
                ('characters', models.ManyToManyField(blank=True, to='app.character')),
                ('stories', models.ManyToManyField(blank=True, to='app.story')),
            ],
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='author_title_constraint'),
        ),
    ]
