# Generated by Django 5.0.6 on 2024-06-02 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.UUIDField(db_column='story_id', default=uuid.uuid4, editable=False)),
                ('story_rank', models.AutoField(db_column='story_rank', default=0, primary_key=True, serialize=False, unique=True)),
                ('story_title', models.CharField(db_column='story_title', default='Story Title', help_text='Enter your story title.', max_length=250)),
                ('story_ideas', models.JSONField(db_column='story_ideas', help_text='The list of ideas which make up your story.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('idea_id', models.UUIDField(db_column='idea_id', default=uuid.uuid4, editable=False)),
                ('idea_rank', models.AutoField(db_column='idea_rank', default=0, primary_key=True, serialize=False, unique=True)),
                ('idea_description', models.CharField(db_column='idea_description', default='Idea Description', help_text='Write a brief description of your idea.', max_length=500)),
                ('idea_text', models.TextField(db_column='idea_text', default='Idea Text', help_text='Write anything you want to about your idea.')),
                ('idea_image', models.ImageField(db_column='idea_image', help_text='Upload an image to visualize your idea.', null=True, upload_to='')),
                ('idea_links', models.JSONField(db_column='idea_links', help_text='A list of links to your idea references.', null=True)),
                ('idea_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.story')),
            ],
        ),
    ]
