# Generated by Django 5.0.6 on 2024-11-17 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='plot_points',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='stories',
        ),
        migrations.AddField(
            model_name='plot',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.story'),
        ),
        migrations.AddField(
            model_name='plotpoint',
            name='plot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.plot'),
        ),
        migrations.AlterField(
            model_name='character',
            name='body_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='ethnicity',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='eye_color',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='middle_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.story'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='genre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='premise',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
