# Generated by Django 5.0.6 on 2025-01-29 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='author_title_constraint'),
        ),
    ]
