# Generated by Django 5.0.6 on 2025-01-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_story_title_story_author_title_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
