# Generated by Django 5.0.6 on 2024-11-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_genre_story_genres_alter_story_premise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotpoint',
            name='scenes',
        ),
        migrations.AddField(
            model_name='scene',
            name='plot_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.plotpoint'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='story',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='app.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='genres',
            field=models.CharField(null=True),
        ),
    ]
