# Generated by Django 5.0.6 on 2025-01-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
