# Generated by Django 5.0.6 on 2024-11-30 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_plotpoint_scenes_scene_plot_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='plot_point',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.plotpoint'),
        ),
    ]
