# Generated by Django 5.0.6 on 2024-12-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_scene_plot_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='enneagram_personality',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='mbti_personality',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
