# Generated by Django 5.0.6 on 2025-03-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_character_enneagram_personality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='premise',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
