# Generated by Django 5.0.6 on 2024-12-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_character_enneagram_personality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='full_name',
            field=models.CharField(null=True),
        ),
    ]
