# Generated by Django 5.0.6 on 2024-12-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_character_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='body_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='enneagram_personality',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='eye_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='mbti_personality',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plot',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plotpoint',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scene',
            name='characters',
            field=models.ManyToManyField(blank=True, to='app.character'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='plot_point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.plotpoint'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='characters',
            field=models.ManyToManyField(blank=True, to='app.character'),
        ),
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='genres',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='world',
            name='characters',
            field=models.ManyToManyField(blank=True, to='app.character'),
        ),
        migrations.AlterField(
            model_name='world',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='world',
            name='stories',
            field=models.ManyToManyField(blank=True, to='app.story'),
        ),
    ]
