# Generated by Django 5.0.6 on 2024-12-05 02:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_character_enneagram_personality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
