# Generated by Django 5.0.6 on 2024-12-05 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_story_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='characters',
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.story'),
        ),
    ]
