# Generated by Django 5.0.6 on 2024-12-06 03:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_scene_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, default=list, size=None),
        ),
    ]
