# Generated by Django 5.0.6 on 2024-12-08 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_scene_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='plot',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='app.plot'),
        ),
    ]
