# Generated by Django 5.0.6 on 2024-12-08 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_plot_story_story_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='plot',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='app.plot'),
        ),
    ]
