# Generated by Django 5.0.6 on 2024-12-08 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_story_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='plot',
        ),
        migrations.AddField(
            model_name='plot',
            name='story',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='app.story'),
        ),
    ]
