# Generated by Django 5.0.6 on 2024-12-08 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_story_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='plot',
        ),
        migrations.AddField(
            model_name='plot',
            name='story',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='app.story'),
        ),
    ]
