# Generated by Django 5.0.6 on 2024-12-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_story_plot_plot_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotpoint',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scene',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
