# Generated by Django 5.0.6 on 2024-12-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_plotpoint_order_scene_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
