# Generated by Django 5.0.6 on 2024-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_character_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotpoint',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='scene',
            name='order',
            field=models.SmallIntegerField(blank=True, default=0, unique=True),
        ),
    ]
