# Generated by Django 5.0.6 on 2024-12-22 23:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_plot_point_scene_plotpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='personality_traits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
